export const ADD_ITEM_TO_BOOKING_REQUEST = 'ADD_ITEM_TO_BOOKING_REQUEST'
export const ADD_ITEM_TO_BOOKING_SUCCESS = 'ADD_ITEM_TO_BOOKING_SUCCESS'
export const ADD_ITEM_TO_BOOKING_FAILURE = 'ADD_ITEM_TO_BOOKING_FAILURE'

export const GET_BOOKING_REQUEST = 'GET_BOOKING_REQUEST'
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS'
export const GET_BOOKING_FAILURE = 'GET_BOOKING_FAILURE'

export const REMOVE_BOOKING_REQUEST = 'REMOVE_BOOKING_REQUEST'
export const REMOVE_BOOKING_SUCCESS = 'REMOVE_BOOKING_SUCCESS'
export const REMOVE_BOOKING_FAILURE = 'REMOVE_BOOKING_FAILURE'

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST'
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS'
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE'

