export const FIND_PACKAGE_BY_ID_REQUEST = 'FIND_PACKAGE_BY_ID_REQUEST'
export const FIND_PACKAGE_BY_ID_SUCCESS = 'FIND_PACKAGE_BY_ID_SUCCESS'
export const FIND_PACKAGE_BY_ID_FAILURE = 'FIND_PACKAGE_BY_ID_FAILURE'

export const FIND_PACKAGES_REQUEST = 'FIND_PACKAGES_REQUEST'
export const FIND_PACKAGES_SUCCESS = 'FIND_PACKAGES_SUCCESS'
export const FIND_PACKAGES_FAILURE = 'FIND_PACKAGES_FAILURE'